apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - keycloak-realm-configmap.yaml
  - postgres.yaml
  - mongo.yaml
  - redis.yaml
  - keycloak.yaml
  - backend.yaml
  - frontend.yaml
