apiVersion: v1
kind: Secret
metadata:
  name: autoguide-secrets
  namespace: autoguide
type: Opaque
stringData:
  postgres-db: autoguide
  postgres-user: autoguide
  postgres-password: autoguide
  keycloak-admin-user: admin
  keycloak-admin-password: admin
